#!/bin/bash
# build-protocol-index.sh — Generates @INDEX blocks in protocol files
#
# Each protocol file gets a machine-readable index at the top with section
# names and line ranges. Agents read ONLY the index first, then use
# Read with offset/limit to load specific sections on demand.
#
# Also generates PROTOCOLS-INDEX.md (master cross-file index).
#
# Usage: bash scripts/build-protocol-index.sh
# Run after editing any protocol file to keep indexes current.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PROTO_DIR="$REPO_ROOT/core/protocols"
MASTER="$PROTO_DIR/PROTOCOLS-INDEX.md"

TMP_CLEAN=$(mktemp)
TMP_OUT=$(mktemp)
trap 'rm -f "$TMP_CLEAN" "$TMP_OUT"' EXIT

# Accumulator for master index entries
declare -a MASTER_LINES=()

process_file() {
    local src="$1"
    local name
    name=$(basename "$src")

    # Skip master index
    [ "$name" = "PROTOCOLS-INDEX.md" ] && return

    # 1. Strip existing @INDEX block
    awk '
        /^<!-- @INDEX/ { skip=1; next }
        /^@\/INDEX -->/ { skip=0; next }
        !skip
    ' "$src" > "$TMP_CLEAN"

    # Remove leading blank lines
    local clean
    clean=$(sed '/[^[:space:]]/,$!d' "$TMP_CLEAN")
    echo "$clean" > "$TMP_CLEAN"

    # 2. Find all ## headers (top-level sections only, not ### or deeper)
    local -a titles=()
    local -a line_nums=()
    while IFS= read -r match; do
        local num="${match%%:*}"
        local title="${match#*:## }"
        titles+=("$title")
        line_nums+=("$num")
    done < <(grep -n '^## ' "$TMP_CLEAN" || true)

    local n=${#titles[@]}
    if [ "$n" -eq 0 ]; then
        echo "  SKIP  $name (no ## sections)"
        return
    fi

    local total
    total=$(wc -l < "$TMP_CLEAN" | tr -d ' ')

    # 3. Index block size = 1 (open) + n (entries) + 1 (close) + 1 (blank separator)
    local offset=$((n + 3))

    # 4. Build index block
    local -a idx_lines=()
    idx_lines+=("<!-- @INDEX")

    for ((i = 0; i < n; i++)); do
        # Convert title to TAG: uppercase, spaces→dashes, strip parens/special chars
        local tag
        tag=$(echo "${titles[$i]}" | sed 's/ (.*//' | tr '[:lower:]' '[:upper:]' | tr ' ' '-' | sed 's/[^A-Z0-9-]//g; s/--*/-/g')

        local s=$((${line_nums[$i]} + offset))
        local e
        if ((i + 1 < n)); then
            e=$((${line_nums[$((i + 1))]} + offset - 1))
        else
            e=$((total + offset))
        fi

        idx_lines+=("$(printf '%-40s %d-%d' "$tag" "$s" "$e")")
    done
    idx_lines+=("@/INDEX -->")

    # 5. Write: index block + blank line + clean content
    {
        for line in "${idx_lines[@]}"; do
            echo "$line"
        done
        echo ""
        cat "$TMP_CLEAN"
    } > "$TMP_OUT"

    cp "$TMP_OUT" "$src"
    echo "  OK    $name  ($n sections, index offset=$offset)"

    # 6. Collect entries for master index
    MASTER_LINES+=("")
    MASTER_LINES+=("### $name")
    MASTER_LINES+=("| Section | Lines |")
    MASTER_LINES+=("|----|-----|")

    for ((i = 0; i < n; i++)); do
        local tag
        tag=$(echo "${titles[$i]}" | sed 's/ (.*//' | tr '[:lower:]' '[:upper:]' | tr ' ' '-' | sed 's/[^A-Z0-9-]//g; s/--*/-/g')

        local s=$((${line_nums[$i]} + offset))
        local e
        if ((i + 1 < n)); then
            e=$((${line_nums[$((i + 1))]} + offset - 1))
        else
            e=$((total + offset))
        fi

        MASTER_LINES+=("| $tag | $s-$e |")
    done
}

# --- Main ---
echo "Building protocol section indexes..."
echo ""

for f in "$PROTO_DIR"/*.md; do
    process_file "$f"
done

# 7. Generate master PROTOCOLS-INDEX.md
{
    cat << 'HEADER'
# Protocol Section Index

Agents: read this file to find which protocol file and line range contains the section you need.
Then use `Read` with `offset` and `limit` to load only that section. **Never read entire protocol files.**

Auto-generated by `scripts/build-protocol-index.sh` — do not edit manually.
HEADER
    for line in "${MASTER_LINES[@]}"; do
        echo "$line"
    done
} > "$MASTER"

echo ""
echo "Master index → $MASTER"
echo "Done. Deploy with: bash scripts/setup.sh"
